### PR TITLE
fix bigint math

### LINKED ISSUE #32: Fix integer division in MultisigActorState AmountLocked() method
Issue was created due to comment in PR: 
https://github.com/filecoin-project/specs-actors/pull/30/files#r369708306

### PR DESCRIPTION
**Pull request by zixuanzh**
close #32

### CODE REVIEW

File: actors/builtin/multisig/multisig_actor_state.go [hunk 1]
```diff
@@ -25,9 +25,8 @@ func (st *MultiSigActorState) AmountLocked(elapsedEpoch abi.ChainEpoch) abi.Toke
 		return abi.NewTokenAmount(0)
 	}
 
-	// FIXME: This division is probably incorrect, see issue: https://github.com/filecoin-project/specs-actors/issues/32
-	lockedProportion := (st.UnlockDuration - elapsedEpoch) / st.UnlockDuration
-	return big.Mul(st.InitialBalance, big.NewInt(int64(lockedProportion)))
+	unitLocked := big.Div(st.InitialBalance, big.NewInt(int64(st.UnlockDuration)))
+	return big.Mul(unitLocked, big.Sub(big.NewInt(int64(st.UnlockDuration)), big.NewInt(int64(elapsedEpoch))))
```
Comment (anorth) [inline actors/builtin/multisig/multisig_actor_state.go]: This goes negative as elapsedEpoch increase above unlockDuration. Pull out the subtraction and set a floor at 0.

Comment (zixuanzh) [reply actors/builtin/multisig/multisig_actor_state.go]: that is caught by the return statement at L25
