### PR TITLE
Fix nil penalty big.Int in terminate sectors

### LINKED ISSUE #382: Panic from nil big.Int in terminate sectors
I observed the following stack trace from VM evaluation in go-filecoin on testnet. The bug is in the miner actor, where a `penalty` big.Int is used uninitialized in handleProvingPeriod -> terminateSectors -> burnFundsAndNotifyPedgeChange.

```
goroutine 177 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
    /usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*invocationContext).invoke.func1(0xc0ad0cf7a0, 0xc0af3b7b90, 0x26, 0xc0196c5168, 0xc0196c5178)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/invocation_context.go:166 +0x483
panic(0x5c35a00, 0x79dc4d0)
    /usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
math/big.(*Int).Cmp(0x0, 0xc0b03a8360, 0xc0b03a8340)
    /usr/local/Cellar/go/1.13.6/libexec/src/math/big/int.go:326 +0x26
github.com/filecoin-project/specs-actors/actors/abi/big.Cmp(...)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/abi/big/int.go:121
github.com/filecoin-project/specs-actors/actors/abi/big.Int.GreaterThan(...)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/abi/big/int.go:136
github.com/filecoin-project/specs-actors/actors/builtin/miner.burnFunds(0x6fbf93990, 0xc08bbbab48, 0x0)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/miner/miner_actor.go:1602 +0x3d
github.com/filecoin-project/specs-actors/actors/builtin/miner.burnFundsAndNotifyPledgeChange(0x6fbf93990, 0xc08bbbab48, 0x0)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/miner/miner_actor.go:1597 +0x3f
github.com/filecoin-project/specs-actors/actors/builtin/miner.terminateSectors(0x6fbf93990, 0xc08bbbab48, 0xc0af90ed80, 0x0)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/miner/miner_actor.go:1306 +0x3ca
github.com/filecoin-project/specs-actors/actors/builtin/miner.handleProvingPeriod(0x6fbf93990, 0xc08bbbab48)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/miner/miner_actor.go:983 +0x547
github.com/filecoin-project/specs-actors/actors/builtin/miner.Actor.OnDeferredCronEvent(0x6fbf93990, 0xc08bbbab48, 0xc0af329570, 0x5df6ac0)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/miner/miner_actor.go:916 +0xca
reflect.Value.call(0x5bf0fa0, 0xc0af3ca290, 0x13, 0x5e496ea, 0x4, 0xc0af3bdbc0, 0x2, 0x2, 0xc0196c4e38, 0x495942a, ...)
    /usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x5bf0fa0, 0xc0af3ca290, 0x13, 0xc0af3bdbc0, 0x2, 0x2, 0x2, 0xc0af3bdbc0, 0xc08bbbab50)
    /usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/dispatch.(*actorDispatcher).Dispatch(0xc0af3c2e60, 0xc, 0x5df6ac0, 0xc08bbbab48, 0x5c27d40, 0xc0af3a94c0, 0x0, 0x0, 0x0, 0x0)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/dispatch/dispatch.go:77 +0x2af
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*invocationContext).invoke(0xc0ad0cf7a0, 0x0, 0x0, 0x0)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/invocation_context.go:217 +0x43c
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*invocationContext).Send(0xc0ae9c4630, 0xc0aee78974, 0x4, 0xc, 0x6172940, 0xc0af3a94c0, 0xc0af3a94a0, 0x5be2060, 0x1, 0xc0af3a94c0)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/invocation_context.go:452 +0x292
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*runtimeAdapter).Send(0xc096829240, 0xc0aee78974, 0x4, 0xc, 0x6172940, 0xc0af3a94c0, 0xc0af3a94a0, 0x61728a0, 0xc0af3a08e0, 0x0)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/runtime_adapter.go:96 +0x77
github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.processDeferredCronEvents(0x6fbf93990, 0xc096829240, 0x1, 0x1)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/power/power_actor.go:435 +0x290
github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.OnEpochTickEnd(0x6fbf93990, 0xc096829240, 0x0, 0x5df6ac0)
    /Users/me/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.5.3/actors/builtin/power/power_actor.go:327 +0xa4
reflect.Value.call(0x5bf1cc0, 0xc0aee78000, 0x13, 0x5e496ea, 0x4, 0xc0aee6e630, 0x2, 0x2, 0x5c3faa0, 0xc0aee72601, ...)
    /usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x5bf1cc0, 0xc0aee78000, 0x13, 0xc0aee6e630, 0x2, 0x2, 0x2, 0xc0aee6e630, 0x196)
    /usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/dispatch.(*actorDispatcher).Dispatch(0xc0aee725c0, 0xa, 0x5df6ac0, 0xc096829240, 0x0, 0x0, 0x0, 0x44f109f, 0xc0aee53000, 0x5c3d820)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/dispatch/dispatch.go:77 +0x2af
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*invocationContext).invoke(0xc0ae9c4630, 0x0, 0x0, 0x0)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/invocation_context.go:217 +0x43c
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*invocationContext).Send(0xc0ae9c45a0, 0xc0aee58370, 0x2, 0xa, 0x0, 0x0, 0xc0aee53020, 0xc0aee53020, 0x0, 0xc0aee53020)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/invocation_context.go:452 +0x292
github.com/filecoin-project/go-filecoin/internal/pkg/vm/internal/vmcontext.(*runtimeAdapter).Send(0xc096829138, 0xc0aee58370, 0x2, 0xa, 0x0, 0x0, 0xc0aee53020, 0xc0196c5f38, 0x40cfb0c, 0x5c3faa0)
    /Users/me/plabs/src/go-filecoin-1/internal/pkg/vm/internal/vmcontext/runtime_adapter.go:96 +0x77
github.com/filecoin-project/specs-actors/actors/builtin/cron.Actor.EpochTick(0x6fbf93990, 0xc096829138, 0x7a3a998, 0x5df6ac0)
```

### PR DESCRIPTION
**Pull request by anorth**
Changes a bunch of possibly-nil values to make them less nil. Fixes #382.

@whyrusleeping we need to think about whether this can be introduced into testnet without an explicit upgrade. The error will have made the block un-validatable. Since it came from cron, it's probably unavoidable. What did Lotus do?

### CODE REVIEW

File: actors/builtin/miner/miner_actor.go [hunk 1]
```diff
@@ -1245,8 +1246,7 @@ func terminateSectors(rt Runtime, sectorNos *abi.BitField, terminationType power
 	var dealIDs []abi.DealID
 	var allSectors []*SectorOnChainInfo
 	var faultySectors []*SectorOnChainInfo
-	var penalty abi.TokenAmount
-
+	penalty := abi.NewTokenAmount(0)
```
Comment (anorth) [inline actors/builtin/miner/miner_actor.go:1249]: This is the one I observed being evaluated. It's uninitialized if the termination type is `SectorTerminationExpired`.
