### PR TITLE
Fix/prove commit aggregate len check

### LINKED ISSUE #1442: ProveCommitAggregate: Check `len(precommits)` prior to index access
#### Description

https://github.com/filecoin-project/specs-actors/blob/a9f9f95f5e93bb7a27fd9fe8c0217e347fa1bef9/actors/builtin/miner/miner_actor.go#L945-L946

The above check can never be triggered. If `len(precommits) == 0`, the index access in the previous line will cause a panic.

#### Recommendation

Switch the order of the lines and/or move the length check to be above the loops over `precommits`: https://github.com/filecoin-project/specs-actors/blob/a9f9f95f5e93bb7a27fd9fe8c0217e347fa1bef9/actors/builtin/miner/miner_actor.go#L887-L888

### PR DESCRIPTION
**Pull request by ZenGround0**
Fixes #1442

### CODE REVIEW

File: actors/builtin/miner/miner_actor.go [hunk 1]
```diff
@@ -942,8 +942,8 @@ func (a Actor) ProveCommitAggregate(rt Runtime, params *ProveCommitAggregatePara
 		svis = append(svis, svi)
 	}
 
-	sealProof := precommits[0].Info.SealProof
 	builtin.RequireState(rt, len(precommits) > 0, "bitfield non-empty but zero precommits read from state")
+	sealProof := precommits[0].Info.SealProof
```
Comment (ZenGround0) [inline actors/builtin/miner/miner_actor.go:946]: Note this should be strictly impossible since GetAllPrecommittedSectors should error and cause an abort before reaching here so I can't test.

**Review by Stebalien — APPROVED** [review]
