### PR TITLE
Bug/sector expiry checks new expiry is valid

### LINKED ISSUE #394: ExtendSectorExpiration func don't check sector.Info.Expiration
in PreCommitSector, I saw that 
``` go
// Check expiry is exactly *the epoch before* the start of a proving period.
periodOffset := st.ProvingPeriodStart % WPoStProvingPeriod
expiryOffset := (params.Expiration + 1) % WPoStProvingPeriod
```
but there is no check in ExtendSectorExpiration, maybe that's  forgotten

### PR DESCRIPTION
**Pull request by acruikshank**
closes #394

### Motivation

Expiration for a sector must be set to the epoch before the proving period start. This is validated in `PreCommitSector`, but not in `ExtendSectorExpiration`.

### Proposed Changes

1. Execute the same validation in `ExtendSectorExpiration` by extracting it as a function in `miner.Actor`.
2. Test.

### CODE REVIEW

File: actors/builtin/miner/miner_actor.go [hunk 1]
```diff
@@ -1221,6 +1226,16 @@ func computeFaultsFromMissingPoSts(st *State, deadlines *Deadlines, sinceDeadlin
 	return
 }
 
+// Check expiry is exactly *the epoch before* the start of a proving period.
+func validateExpiration(st State, expiration abi.ChainEpoch, rt Runtime) {
```
Comment (anorth) [inline actors/builtin/miner/miner_actor.go:1230]: Pass `State` as a pointer, not value.

For consistency with other methods, pass `rt` as the first parameter. But better generally would be to return an error from this function and do the abort directly in the actor method, avoding the `rt` parameter. As a policy, it makes these methods callable without needing a runtime (but there are cases where it's pragmatic to ignore).

File: actors/builtin/miner/miner_test.go [hunk 2]
```diff
@@ -390,6 +390,112 @@ func TestProvingPeriodCron(t *testing.T) {
...
+
+		func() {
+			defer func() {
+				r := recover()
+				require.NotNil(t, r)
+				assert.Contains(t, fmt.Sprintf("%s",r), "invalid expiration")
+			}()
+
+			actor.extendSector(rt, sector, uint64(extension), params)
+		}()
```
Comment (anorth) [inline actors/builtin/miner/miner_test.go:445]: Use `rt.ExpectAbort`.

As my comment in #435 , combine this with other test cases to reduce the set-up.

File: actors/builtin/miner/miner_test.go [hunk 3]
```diff
@@ -390,6 +390,112 @@ func TestProvingPeriodCron(t *testing.T) {
...
+	st := getState(rt)
+	deadline := st.DeadlineInfo(rt.Epoch())
+	expiration := deadline.PeriodEnd() + 10*miner.WPoStProvingPeriod
+	sectorInfo := a.commitAndProveSectors(rt, 1, expiration, big.Zero())
+
+	sector, found, err := getState(rt).GetSector(rt.AdtStore(), sectorInfo[0].SectorNumber)
+	require.NoError(t, err)
+	require.True(t, found)
+	return rt, st, expiration, sector
+}
```
Comment (anorth) [inline actors/builtin/miner/miner_test.go:497]: I don't love this approach, because it makes these setup functions easy to abuse as a blunt way to set up other, unrelated tests, which leads to unwanted coupling between the tests and general maintenance pain. This is based on my experience working with existing uses of the pattern in go-filecoin.

I think there probably is room to factor out some generic set-up code more than is already done, but I would want to do so in a way that is explicitly not coupled to any particular tests, probably some kind of builder pattern.

In this case, I'd prefer to share the setup code by just testing multiple conditions in the one test case. E.g. see TestCommitSector.
