### PR TITLE
VerifReg: Audit Fixes

### LINKED ISSUE #722: Verifreg: Disallow RootKey from assuming other roles
Currently, RootKey can be added as a Verified or as a VerifiedClient. In order to minimize permissions for this critical role, `AddVerifier` and `AddVerifiedClient` should fail for this case.

### LINKED ISSUE #724: Verifreg.AddVerifier: params.Allowance should be greater than or equal to MinVerifiedDealSize
Currently, Verifiers can be added whose allowance doesn't even allow them to add a VerifiedClient. By enforcing that `params.Allowance >= MinVerifiedDealSize`, this should never happen.

### LINKED ISSUE #725: Verifreg.AddVerifiedClient: Existing Verifiers should not be able to become VerifiedClients
Another role-segregation recommendation similar to #722 - `Verifiers` should not be addable in the `AddVerifiedClient` method.

### LINKED ISSUE #726: Verifreg.AddVerifiedClient: Misleading parameter "MinVerifiedDealSize"
Currently, `AddVerifiedClient` fails if the new verified client has an allowance less than or equal to `MinVerifiedDealSize`:

https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L90-L92

This seems misleading. I recommend changing this to strictly "less than"

### LINKED ISSUE #728: Verifreg.UseBytes: Consider never deleting a VerifiedClient entry
As I understand, VerifiedClients should only ever be given one allowance, and this should never change. From code comments:

https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L116-L119

However, deleted VerifiedClients can be re-added by a Verifier via `AddVerifiedClient`.

Additionally, `RestoreBytes` has the authority to create VerifiedClients:

https://github.com/filecoin-project/specs-actors/blob/8c473f656bb07b19c61991f452d1e57d59dc5083/actors/builtin/verifreg/verified_registry_actor.go#L192

In the event of a significant issue with StorageMarket code, this authority may provide an attacker with an additional vector into the Verifreg system.

#### Recommendation

Don't delete VerifiedClient entries.

(Related to #727)

### PR DESCRIPTION
**Pull request by aarshkshah1992**
Closes #722 .
Closes #724 .
Closes #725 .
Closes #726 
Closes #728 .

@wadeAlexC.

### CODE REVIEW

**Comment by wadeAlexC** [comment]
The main concern I have so far is that `st.Rootkey` isn't explicitly required to be an ID address, and neither are any of the input `params.Address`. 

Given discussion in #556, we may be able to rely on input addresses being resolved to an ID address.

Maybe we should add an explicit check in the Constructor to ensure that `RootKey` is an ID address?

File: actors/builtin/verifreg/verified_registry_actor.go [hunk 1]
```diff
@@ -129,9 +148,9 @@ func (a Actor) AddVerifiedClient(rt vmr.Runtime, params *AddVerifiedClientParams
 			rt.Abortf(exitcode.ErrIllegalState, "Failed to update new verifier cap (%d) for %v", newVerifierCap, verifierAddr)
 		}
 
-		// Write-once entry and does not get changed for simplicity.
-		// If parties neeed more allowance, they can get another VerifiedClient account.
 		// This is a one-time, upfront allocation.
+		// This allowance cannot be changed by calls to AddVerifiedClient as long as the client has not been removed.
+		// If parties need more allowance, it be added via a call to RestoreBytes.
```
Comment (wadeAlexC) [inline actors/builtin/verifreg/verified_registry_actor.go:153]: This isn't really accurate. RestoreBytes is only called in the event that the client already had and used this allowance, but the deal timed out

File: actors/builtin/verifreg/verified_registry_actor.go [hunk 2]
```diff
@@ -228,12 +247,27 @@ func (a Actor) RestoreBytes(rt vmr.Runtime, params *RestoreBytesParams) *adt.Emp
 	}
 
 	var st State
+	rt.State().Readonly(&st)
+	if st.RootKey == params.Address {
+		rt.Abortf(exitcode.ErrIllegalArgument, "Cannot restore allowance for Rootkey")
+	}
```
Comment (wadeAlexC) [inline actors/builtin/verifreg/verified_registry_actor.go:253]: Will this ever catch anything?

I think that currently, the market actor sends this method a non-ID address, because it's the same address used to verify a client's signature over a DealProposal.

This may not catch anything, because (I think) RootKey is supposed to be an ID address.

Comment (wadeAlexC) [reply actors/builtin/verifreg/verified_registry_actor.go:253]: On second thought, this should probably be removed. The market actor uses this during its cron tick - an abort here may allow someone to force a cron tick failure.

Comment (wadeAlexC) [reply actors/builtin/verifreg/verified_registry_actor.go:253]: Same goes for the change below.

Comment (wadeAlexC) [reply actors/builtin/verifreg/verified_registry_actor.go:253]: What if instead of removing these, we just removed the "RequireSuccess" condition from the market actor's cron tick?

**Comment by anorth** [comment]
Yes, we can and should constrain `Rootkey` to be an ID address, since we'll know it at genesis state construction.

File: actors/builtin/verifreg/verified_registry_actor.go [hunk 3]
```diff
@@ -50,10 +50,17 @@ type AddVerifierParams struct {
...
 func (a Actor) AddVerifier(rt vmr.Runtime, params *AddVerifierParams) *adt.EmptyValue {
+	if params.Allowance.LessThan(MinVerifiedDealSize) {
+		rt.Abortf(exitcode.ErrIllegalArgument, "Allowance %d below MinVerifiedDealSize for add verifier %v", params.Allowance, params.Address)
+	}
+
 	var st State
 	rt.State().Readonly(&st)
 	rt.ValidateImmediateCallerIs(st.RootKey)
 
+	if params.Address == st.RootKey {
```
Comment (anorth) [inline actors/builtin/verifreg/verified_registry_actor.go:61]: Please TODO and reference https://github.com/filecoin-project/specs-actors/issues/556 here and anywhere a user-provided address is inspected. Until we do that, this isn't really enforced.

File: actors/builtin/verifreg/verified_registry_actor.go [hunk 4]
```diff
@@ -119,6 +131,13 @@ func (a Actor) AddVerifiedClient(rt vmr.Runtime, params *AddVerifiedClientParams
 			rt.Abortf(exitcode.ErrNotFound, "Invalid verifier %v", verifierAddr)
 		}
 
+		// Validate client to be added isn't a verifier
+		found, err = verifiers.Get(AddrKey(params.Address), nil)
+		builtin.RequireNoErr(rt, err, exitcode.ErrIllegalState, "failed to get verifier")
+		if found {
+			rt.Abortf(exitcode.ErrIllegalArgument, "verifier %v cannot be added as a verified client", params.Address)
+		}
```
Comment (anorth) [inline actors/builtin/verifreg/verified_registry_actor.go:139]: Blocking: unless we also constrain AddVerifier to prevent existing clients, we won't have an invariant.

File: actors/builtin/verifreg/verified_registry_actor.go (hunk 2 above)
Comment (anorth) [reply actors/builtin/verifreg/verified_registry_actor.go:253]: The market is supposed to resolve these, but verified registry implementation violated this for UseBytes: https://github.com/filecoin-project/specs-actors/issues/768. This case, called from cron, can rely on the ID address and so should check and enforce it.

This implicitly means that, unlike multisig parties, we do require deal participants to have instantiated account actors (fyi @arajasek)

File: actors/builtin/verifreg/verified_registry_test.go [hunk 5]
```diff
@@ -246,6 +275,31 @@ func TestAddVerifiedClient(t *testing.T) {
...
+		// add verified client with caller 1
+		verifier := ac.addNewVerifier(rt, verifierAddr, allowance)
+		client := ac.mkClientParams(verifierAddr, clientAllowance)
+		rt.SetCaller(verifier.Address, builtin.VerifiedRegistryActorCodeID)
+		rt.ExpectValidateCallerAny()
+		rt.ExpectAbort(exitcode.ErrIllegalArgument, func() {
+			rt.Call(ac.AddVerifiedClient, client)
+		})
+		rt.Verify()
+	})
```
Comment (anorth) [inline actors/builtin/verifreg/verified_registry_test.go:302]: Test the opposite order too

File: actors/builtin/verifreg/verified_registry_actor.go (hunk 3 above)
Comment (aarshkshah1992) [reply actors/builtin/verifreg/verified_registry_actor.go:61]: This is done for all methods that need this check.

File: actors/builtin/verifreg/verified_registry_actor.go (hunk 4 above)
Comment (aarshkshah1992) [reply actors/builtin/verifreg/verified_registry_actor.go:139]: This is done.

File: actors/builtin/verifreg/verified_registry_actor.go (hunk 3 above)
Comment (aarshkshah1992) [reply actors/builtin/verifreg/verified_registry_actor.go:61]: This is done everywhere.

File: actors/builtin/verifreg/verified_registry_actor.go (hunk 4 above)
Comment (aarshkshah1992) [reply actors/builtin/verifreg/verified_registry_actor.go:139]: This has been done.

File: actors/builtin/verifreg/verified_registry_test.go (hunk 5 above)
Comment (aarshkshah1992) [reply actors/builtin/verifreg/verified_registry_test.go:302]: This is done.

File: actors/builtin/verifreg/verified_registry_actor.go (hunk 1 above)
Comment (aarshkshah1992) [reply actors/builtin/verifreg/verified_registry_actor.go]: Have fixed this.

**Comment by aarshkshah1992** [comment]
@anorth @wadeAlexC 

Have address all comments. We now mandate that that the `RootKey` be resolvable to an ID address and fail the construction of the actor if is not. Please approve if happy.

With regards to resolving all `Verifier` and `VerifiedClients` to ID addresses before comparing them with the `RootKey`, I think https://github.com/filecoin-project/specs-actors/issues/556#issuecomment-662848447 is decent solution.

File: actors/builtin/verifreg/verified_registry_test.go [hunk 6]
```diff
@@ -20,32 +20,74 @@ func TestExports(t *testing.T) {
...
-	actor := verifreg.Actor{}
 	receiver := tutil.NewIDAddr(t, 100)
-	builder := mock.NewBuilder(context.Background(), receiver).
-		WithCaller(builtin.SystemActorAddr, builtin.InitActorCodeID)
 
-	rt := builder.Build(t)
+	runtimeSetup := func() *mock.Runtime {
+		builder := mock.NewBuilder(context.Background(), receiver).
+			WithCaller(builtin.SystemActorAddr, builtin.InitActorCodeID)
+		rt := builder.Build(t)
```
Comment (anorth) [inline actors/builtin/verifreg/verified_registry_test.go:28]: This is incorrect: the `t` must come from the `t.Run`, not the outer scope.

You could pass it as an arg, but it's just confusing. Do make the builder outside, but then just do `builder.Build(t)` inside `t.Run`.

**Comment by anorth** [comment]
Thanks. I'll try to reach a decision about auto-creating new actor accounts shortly.

File: actors/builtin/verifreg/verified_registry_actor.go [hunk 7]
```diff
@@ -228,12 +265,29 @@ func (a Actor) RestoreBytes(rt vmr.Runtime, params *RestoreBytesParams) *adt.Emp
...
+
 	rt.State().Transaction(&st, func() interface{} {
 		verifiedClients, err := adt.AsMap(adt.AsStore(rt), st.VerifiedClients)
 		builtin.RequireNoErr(rt, err, exitcode.ErrIllegalState, "failed to load verified clients")
 
+		verifiers, err := adt.AsMap(adt.AsStore(rt), st.Verifiers)
+		builtin.RequireNoErr(rt, err, exitcode.ErrIllegalState, "failed to load verifiers")
+
+		// validate we are NOT attempting to do this for a verifier
+		found, err := verifiers.Get(AddrKey(params.Address), nil)
```
Comment (Stebalien) [inline actors/builtin/verifreg/verified_registry_actor.go:283]: This check seems expensive (loads a HAMT) and pointless. Are we expecting this case to be possible @aarshkshah1992?
