### PR TITLE
Market: Miner fixes and tests

### LINKED ISSUE #589: Market Actor: Should we be able to Terminate the same deals twice
Currently, it is possible to mark the same deal as terminated twice by calling `OnMinerSectorsTerminate` twice with the same dealID. The `SlashEpoch` on the deal will be the last `CurrentEpoch` it was called at.

Is this the expected behaviour ?

@anorth

### PR DESCRIPTION
**Pull request by aarshkshah1992**
Closes #589 AND #603 .

Also, as discussed offline with @anorth , we don't need to check for negative balance in the `AddBalanceCall` as the Runtime will enforce it.

### CODE REVIEW

File: actors/builtin/market/market_test.go [hunk 1]
```diff
@@ -971,6 +958,52 @@ func TestOnMinerSectorsTerminate(t *testing.T) {
...
+		// provider1 publishes deal1 and 2 and deal3 -> deal3 has the lowest endepoch
+		dealId1 := actor.generateAndPublishDeal(rt, client, mAddrs, startEpoch, endEpoch)
+		dealId2 := actor.generateAndPublishDeal(rt, client, mAddrs, startEpoch, endEpoch+1)
+		dealId3 := actor.generateAndPublishDeal(rt, client, mAddrs, startEpoch, endEpoch-1)
+		actor.activateDeals(rt, sectorExpiry, provider, currentEpoch, dealId1, dealId2, dealId3)
+
+		// terminating the deal so slash epoch is the current epoch
+		actor.terminateDeals(rt, provider, dealId1)
+
+		// set a new epoch and terminate again -> however slash epoch will still be the old epoch.
```
Comment (ZenGround0) [inline actors/builtin/market/market_test.go:992]: nit: slash epoch for dealID1 will still be the old epoch

Comment (aarshkshah1992) [reply actors/builtin/market/market_test.go:992]: Will do this in a follow-up.
