### PR TITLE
Enforce locked funds do not fall below initial pledges

### LINKED ISSUE #415: Implement verification of locked pledge requirements on PoRep and PoSt
A miner must maintain locked pledge collateral equal to the sum of the initial pledge for all sectors (to cover potential fees from failing all PoSts and having sectors terminated, though because block reward is dynamic, this isn't a strong guarantee).  The pledge requirement should be checked upon the explicit miner worker messages of ~submitting a PoSt and~ proving a new sector commitment, and withdrawing unlocked balance.

There's a placeholder function unimplemented for this. Note that the call site for sector commitment was jumbled in the implementation of batched porep verifications, and should probably move back to be in the explicit miner-initiated call path (PreCommitSector), rather than in cron.

### PR DESCRIPTION
**Pull request by acruikshank**
closes #415

### Motivation

We need to enforce that a miner's locked funds exceeds the sum of their initial pledges to ensure the miner has enough funds to over potential fees. To do this we need to track the sum of initial pledges (and maintain that sum). We will check lock funds against initial pledges before a miner proves a sector and before the miner withdraws funds.

### Proposed Changes

The bulk of this PR breaks out into its 5 initial commits:

1. Add `InitialPledges` to `miner.State` and add to it every time a sector is proven.
2. Add `InitialPledge' to 'SectorOnChainInfo' and set it to the sector's initial pledge when proven.
3. Use the sector's `InitialPledge` to subtract from `miner.State.InitialPledges` when sectors are terminated.
4. Add a check in `ProveCommitSector` to ensure locked funds are sufficient relative to initial pledges.
5. Do the same in `WithdrawFunds`.

All of these changes are tested. This required some new infrastructure in miner test.

### CODE REVIEW

File: actors/builtin/miner/miner_test.go [hunk 1]
```diff
@@ -637,6 +682,94 @@ func TestExtendSectorExpiration(t *testing.T) {
...
+		precommitEpoch := abi.ChainEpoch(1)
+		rt.SetEpoch(precommitEpoch)
+		st := getState(rt)
+		deadline := st.DeadlineInfo(rt.Epoch())
+		expiration := deadline.PeriodEnd() + 100*miner.WPoStProvingPeriod
+		sectorInfo := actor.commitAndProveSectors(rt, 1, expiration, 0, nil)
+
+		sector, found, err := getState(rt).GetSector(rt.AdtStore(), sectorInfo[0].SectorNumber)
+		require.NoError(t, err)
+		require.True(t, found)
```
Comment (anorth) [inline actors/builtin/miner/miner_test.go:709]: This looks inconvenient. We should just change commitAndProveSectors to return the SectorOnChainInfos.

File: support/mock/mockrt.go [hunk 2]
```diff
@@ -585,6 +585,10 @@ func (rt *Runtime) GetState(o runtime.CBORUnmarshaler) {
 	}
 }
 
+func (rt *Runtime) SetStateForTesting(o runtime.CBORMarshaler) {
```
Comment (anorth) [inline support/mock/mockrt.go:588]: Move this method into the "mocking facilities" section. 

Since it's a mock the `ForTesting` is probably implicit. Maybe `ReplaceState`? or `OverwriteState`?

File: actors/builtin/miner/miner_state.go [hunk 3]
```diff
@@ -320,6 +323,20 @@ func (st *State) DeleteSectors(store adt.Store, sectorNos *abi.BitField) error {
 	return err
 }
 
+func (st *State) DeductPledges(store adt.Store, sectorNos *abi.BitField) error {
+	return sectorNos.ForEach(func(sectorNo uint64) error {
+		sector, found, err := st.GetSector(store, abi.SectorNumber(sectorNo))
```
Comment (anorth) [inline actors/builtin/miner/miner_state.go:328]: Blocking: Unfortunately this is hiding a potentially huge performance issue inside the state class. Loading an arbitrary number of sector infos is unreasonable. This will need to be replaced as part of #411, using a similar technique, and the logic will need to move. In order to make that easier later, please let's not put it inside the state class. cc @Stebalien 

- Remove this method, do the work in the actor code and then use `AddInitialPledge(pledgeToRemove.Neg())`.
- Remove the call site from `removeTerminatedSectors` and pull up to `terminateSectors`. That method _already_ loads all these infos, so accumulate the pledge delta there and then call the cheap state mutation

File: actors/builtin/miner/miner_test.go [hunk 4]
```diff
@@ -405,6 +409,49 @@ func TestWindowPost(t *testing.T) {
 	})
 }
 
+func TestProveCommit(t *testing.T) {
+	periodOffset := abi.ChainEpoch(100)
+	actor := newHarness(t, periodOffset)
+	builder := builderForHarness(actor).
+		WithCaller(builtin.InitActorAddr, builtin.InitActorCodeID).
```
Comment (anorth) [inline actors/builtin/miner/miner_test.go:416]: `constructAndVerify` does this now, so you shouldn't need this line.
