### PR TITLE
Payment: Audit and fixes

### LINKED ISSUE #660: PaymentChannel: Reject equal-nonce voucher submissions
`UpdateChannelState` currently allows a voucher with equivalent nonce to the last-seen nonce to be submitted and processed:

https://github.com/filecoin-project/specs-actors/blob/1b19d168503d7401e10c94632a3e1dbdede5d692/actors/builtin/paych/paych_actor.go#L205-L207

While this may not result in a loss of funds, this replayability complicates the possible operations of `UpdateChannelState` significantly.

### LINKED ISSUE #709: Set a sensible payment channel settlement delay
It's currently set to 1, which doesn't give the receiver sufficient time to submit their vouchers.

@whyrusleeping what delay do you suggest?

### PR DESCRIPTION
**Pull request by aarshkshah1992**
Closes #660 .
Closes #709 .

Let me know if this makes sense.

### CODE REVIEW

**Comment by aarshkshah1992** [comment]
@wadeAlexC.

**Comment by wadeAlexC** [comment]
LGTM!

File: actors/builtin/paych/paych_actor.go [hunk 1]
```diff
@@ -210,11 +211,13 @@ func (pca Actor) UpdateChannelState(rt vmr.Runtime, params *UpdateChannelStatePa
...
 			st.LaneStates = append(st.LaneStates[:laneIdx], append([]*LaneState{ls}, st.LaneStates[laneIdx:]...)...)
-
+			lanFound = false
 		}
 
-		if ls.Nonce > sv.Nonce {
-			rt.Abortf(exitcode.ErrIllegalArgument, "voucher has an outdated nonce, cannot redeem")
+		if lanFound {
+			if ls.Nonce >= sv.Nonce {
+				rt.Abortf(exitcode.ErrIllegalArgument, "voucher has an outdated nonce, cannot redeem")
```
Comment (anorth) [inline actors/builtin/paych/paych_actor.go:219]: Nit: include the relevant values in the message

File: actors/builtin/paych/paych_test.go [hunk 2]
```diff
@@ -294,6 +295,29 @@ func TestActor_UpdateChannelStateRedeem(t *testing.T) {
...
+		var st1 State
+		rt.GetState(&st1)
+
+		ucp := &UpdateChannelStateParams{Sv: *sv}
+		// requireCreateChannelWithLanes creates a lane with nonce = 1.
+		// reusing that should fail
+		ucp.Sv.Nonce = 1
+		ucp.Sv.Amount = newVoucherAmt
+
+		// Sending to same lane updates the lane with "new" state
```
Comment (anorth) [inline actors/builtin/paych/paych_test.go:310]: Stray comment

File: actors/builtin/paych/paych_actor.go [hunk 3]
```diff
@@ -198,6 +198,7 @@ func (pca Actor) UpdateChannelState(rt vmr.Runtime, params *UpdateChannelStatePa
 	}
 
 	rt.State().Transaction(&st, func() interface{} {
+		lanFound := true
```
Comment (anorth) [inline actors/builtin/paych/paych_actor.go:201]: Nit: `laneFound`

File: actors/builtin/paych/paych_actor.go (hunk 1 above)
Comment (aarshkshah1992) [reply actors/builtin/paych/paych_actor.go]: This is done.

File: actors/builtin/paych/paych_test.go (hunk 2 above)
Comment (aarshkshah1992) [reply actors/builtin/paych/paych_test.go]: Removed.

File: actors/builtin/paych/paych_actor.go (hunk 3 above)
Comment (aarshkshah1992) [reply actors/builtin/paych/paych_actor.go]: Done.
